name: ml-service
services:
  ml-app:
    build:
      context: .
      args:
        TORCH_VARIANT: cpu  # or "cu128" for GPU
    ports:
      - "8000:8000"
    networks:
      - service-network

networks:
  service-network:
